name: Deploy to Production
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  application_code_test:
    name: Application Code Test
    uses: ./.github/workflows/test.yaml
  test_image_deployment:
    needs: application_code_test
    name: Test Image Deployment
    uses: ./.github/workflows/test_image_deployment.yaml
  push_to_registry: 
    name: Push Docker image to Docker Hub
    needs: test_image_deployment
    uses: ./.github/workflows/push_images.yaml
    with:
      ENV_FILE: ${{ vars.ENV_FILE}}
      REGISTRY: ${{ vars.REGISTRY }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  deploy:
    name: Deploy to AWS
    needs: push_to_registry
    uses: ./.github/workflows/deployment.yaml
