name: Deploy to Production
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  check_files:
    runs-on: ubuntu-latest
    name: Check changed files
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checking changed files
        id: check_files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1)

          if [[ $CHANGED_FILES == "README.md" ]]; then
            echo "README file only. Skipping other jobs..."
            echo "::set-output name=skip_jobs::true"
          else
            echo "Other files changed. Continuing with other jobs..."
            echo "::set-output name=skip_jobs::false"
          fi
  application_code_test:
    name: Application Code Test
    needs: check_files
    uses: ./.github/workflows/application_code_test.yaml
  test_image_deployment:
    needs: application_code_test
    name: Test Image Deployment
    uses: ./.github/workflows/test_image_deployment.yaml
  push_to_registry: 
    name: Push Docker image to Docker Hub
    needs: test_image_deployment
    uses: ./.github/workflows/push_images.yaml
    with:
      ENV_FILE: ${{ vars.ENV_FILE}}
      REGISTRY: ${{ vars.REGISTRY }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  deploy:
    name: Deploy to AWS
    needs: push_to_registry
    uses: ./.github/workflows/deployment.yaml
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
